server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:customer-db
    username: garcin
    password: Hello0505
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URI}
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /customer-api/v3/api-docs
  swagger-ui:
    path: /customer-api/swagger-ui.html